### PR TITLE
Make the medbags slightly more costly

### PR DESCRIPTION
**Pull request by Sunconure11**
Prepping for eventual texturework on the weekend

### CODE REVIEW

**Comment by ljfa-ag** [comment]
One more hide and one more string?

**Comment by Sunconure11** [comment]
Pretty much all I could think of, lol

**Comment by Sunconure11** [comment]
I'm working on the totems for Night Vision, but should the spider be the new night vision totem, now that autojump is redundant, or should a different totem be given that use?

**Comment by ljfa-ag** [comment]
Nevermind about that, I didn't realize that autojump was optional.

The important part of the recipe imo is the Totemic materials (buffalo hide, buffalo tooth, cedar plank), and not so much the diamond. They are rather cheap once you get them, but they require Totemic progression first.

**Comment by Sunconure11** [comment]
I see

**Pull request closed without merging**
