### PR TITLE
Added oddly specific definitions for buffalo meat

### PR DESCRIPTION
**Pull request by Sunconure11**

### CODE REVIEW

**Comment by ljfa-ag** [comment]
Do you really think these are needed?

**Comment by Sunconure11** [comment]
Eh, it depends.

The buffalo oredictionary was added based on the fact that a lot of unique meats from the major agricultural mods tend to have their own related oredictionaries, even if they aren't widely used (harvestcraft is an example of such a mod, but beef definitions here are being retained for compatibility).

The iron definition was added in case of any derpy mods that add iron nuggets via that way (natura has weird stick entries for instance)

Hide and teeth are for... well, whoever wants to hook onto those definitions, simply because I could think of the possibility of mods arriving with those definitions. (God I wish we had something like Hunterborn but for minecraft)

**Comment by ljfa-ag** [comment]
I feel like "hideBuffalo" and "teethBuffalo" should be enough, I'm not even sure if it makes sense for them to be in the ore dictionary. It's not like they need to if other mods want to use them.
And I won't add "ironNugget" just because of that possibility, "nuggetIron" is already standard.
But I guess I will add the buffalo meat entries.

**Comment by Sunconure11** [comment]
It should be ready now.

**Pull request merged**
